# Generated by Django 3.2.10 on 2022-01-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_alter_zone_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
