# Generated by Django 3.2.10 on 2022-01-31 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('destination', '0003_alter_zone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photologue.gallery'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photologue.gallery'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photologue.gallery'),
        ),
    ]
